stages:
  - build
  - test

build:
  image: node:12.1.0
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

test_node12:
  image: node:12
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node12
    paths:
      - node_modules/

test_node10:
  image: node:10
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node10
    paths:
      - node_modules/

test_node8:
  image: node:8
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node8
    paths:
      - node_modules/
